### ISSUE TITLE
Mandivi VA Inavalid Header Signature

### ISSUE THREAD

**Issue by amrullahdev** [PTNUSASATUINTIARTHA-DOKU/jokul-php-library#1]
kenapa ketika saya mengguakan mandiri VA yang keluar invalid signature ? 
![image](https://user-images.githubusercontent.com/52965747/116842441-c92ec980-ac06-11eb-8557-f24fb4354d31.png)

![image](https://user-images.githubusercontent.com/52965747/116842628-596d0e80-ac07-11eb-8a22-ac6dee922ead.png)

**Comment by ariefrizkyr** [comment]
Kami baru saja update fixingnya, silakan coba diclone versi `master` dari library ini.

Terima kasih
