### ISSUE TITLE
[question] Cek Status Pemabayran

### ISSUE THREAD

**Issue by amrullahdev** [PTNUSASATUINTIARTHA-DOKU/jokul-php-library#3]
bagaimana cara melakukan pengecekan status pembayaran ?

saya sudah mencoba seperti yang di post man collection di gabung dengan generate signature dari php library
/orders/v1/status/{{kode_invoice_saya}}
tetapi yang saya dapatkan  error seperti gambar berikut
![image](https://user-images.githubusercontent.com/52965747/117260018-d226d180-ae78-11eb-8953-f97eca3fccaf.png)

**Comment by ariefrizkyr** [comment]
Hi @amrullahdev ,

Terima kasih atas feedbacknya! 👍 

Error terjadi karena Check Status API merupakan GET method dimana sesuai dengan dokumentasi Signature untuk GET method tidak menggunakan Digest sebagai komponennya: https://jokul.doku.com/docs/docs/technical-references/generate-signature.

Sedangkan function Generate Signature di Jokul PHP Library saat ini selalu menjadikan Digest sebagai komponen Signature: https://github.com/PTNUSASATUINTIARTHA-DOKU/jokul-php-library/blob/master/src/DOKU/Common/Utils.php

Untuk itu, saya coba buat Pull Request untuk update Generate Signature function agar support untuk GET method.

Coba replace file `vendor/doku/jokul-php-library/src/DOKU/Common/Utils.php` seperti file berikut ini: https://github.com/PTNUSASATUINTIARTHA-DOKU/jokul-php-library/blob/d52e461ce9727b19f9d3d36007f600d6fcd4dc9b/src/DOKU/Common/Utils.php

Lalu coba panggil generate signature function dengan set request body nya `null`:

```
$signature = \DOKU\Common\Utils::generateSignature($headers, $targetPath, null, $secretKey);
```

Jika sudah berhasil, kami akan merge pull request tersebut untuk dimasukkan ke release berikutnya.

Kalau @amrullahdev punya cara solving yang lebih baik untuk issue ini, kami sangat terbuka, silakan ajukan pull request. Terima kasih. 😄

**Comment by amrullahdev** [comment]
ok terimakasih mas atas repon komentarnya  , saya akan coba dari saran dan update terbaru yang telah di sediakan 😄
